# OpenCv
OpenCv (open source computer vision library) is an open source computer visison and machine learning software librray.
The library has more than 2500 optimized algorithms,
Opencv is written natively in c++
initial release June 2000

Install anaconda navigator 
Run as administrator
go to environments 
create environment and install necessary library 

In [2]:
# pip install opecv-python
import cv2
print(cv2.__version__)

4.9.0


In [3]:
import numpy
print(numpy.__version__)

1.24.4


In [4]:
import pandas
print(pandas.__version__)

1.4.4


In [5]:
import matplotlib
print(matplotlib.__version__)

3.5.2


1. How to show image? 
2. Resize image
3. slide show 4 image in one window
4. Multiple images in one window

In [8]:
import cv2
path = r"""C:\Users\aksha_0iafvb0\Downloads\wallpaper.jpg"""

img = cv2.imread(path)       # iamread() used for reading image
cv2.imshow('Image', img)     # iamshow() used for showing image
cv2.waitKey(0)               # if 1 the window will close in 1 sec if 0 then when we press any button then window will close
cv2.destroyAllWindows()

In [9]:
path = r"""C:\Users\aksha_0iafvb0\Downloads\wallpaper.jpg"""

img = cv2.imread(path)   

img = cv2.resize(img, (600,400))   # resize() is used for resizing the image
cv2.imshow('Image', img)    
cv2.waitKey(0)         
cv2.destroyAllWindows()

In [16]:
import os
img_names = os.listdir(r"C:\Users\aksha_0iafvb0\OneDrive\Desktop\company resume")
img_names

['IMG_2586.JPG',
 'IMG_2587 (1).JPG',
 'IMG_2587.JPG',
 'IMG_2588 (1).JPG',
 'IMG_2588.JPG',
 'IMG_2589.JPG',
 'IMG_2591.JPG',
 'IMG_2592.JPG',
 'IMG_2593.JPG',
 'IMG_2615.JPG',
 'IMG_2616.JPG',
 'IMG_2617.JPG',
 'IMG_2618.JPG',
 'IMG_2619.JPG',
 'IMG_2620.JPG',
 'IMG_2621.JPG',
 'IMG_2622.JPG',
 'IMG_2623.JPG',
 'IMG_2624.JPG',
 'IMG_2625.JPG',
 'IMG_2626.JPG',
 'IMG_2627.JPG',
 'IMG_2628.JPG',
 'IMG_2629.JPG',
 'IMG_2630.JPG',
 'IMG_2631.JPG',
 'IMG_2632.JPG',
 'IMG_2650.JPG',
 'IMG_2651.JPG',
 'IMG_2652.JPG',
 'IMG_2653.JPG',
 'IMG_2654.JPG']

In [24]:
import cv2
import os

path = r"C:\Users\aksha_0iafvb0\OneDrive\Desktop\company resume"

# Get list of image files in the directory
for img_name in os.listdir(path):
    img_path_full = os.path.join(path, img_name)

    # Read and process only if it's a valid image
    img = cv2.imread(img_path_full)
    if img is not None:
        img = cv2.resize(img, (1000, 720))
        cv2.imshow('image', img)
        cv2.waitKey(500)  # Wait for a key press to show the next image

cv2.destroyAllWindows()


In [28]:
import numpy as np

for img_name in img_names:
    img_path_full = os.path.join(path,img_name)
    img = cv2.imread(img_path_full)
    img = cv2.resize(img,(300,200))
    img_2 = np.hstack((img,img))     #if we want to add more images vertically ((img,img,img)) continuously give ,img
    img_4 = np.vstack((img_2,img_2))  # if we want vertically more imgae ,img_2  addd 
    cv2.imshow('4 Image', img_4)
    cv2.waitKey(500)
    
cv2.destroyAllWindows()

# Video/Camera Play
1. how to play video
2. how to access camera
3. howw to play multiple video/camera in one window

In [29]:
import numpy as np
import cv2
video_path1 = r"C:\Users\aksha_0iafvb0\OneDrive\Desktop\photos\IMG_2582.MOV"
video_path2 = r"C:\Users\aksha_0iafvb0\Downloads\videoplayback.webm"

In [37]:
cap = cv2.VideoCapture(video_path1)

while cap.isOpened():
    ret, frame = cap.read()
    if ret:
        
        image = cv2.resize(frame,(400 ,500))
    
        cv2.imshow('video player',image)
        
        if cv2.waitKey(25) & 0xff == ord('q'):
            break
    else:
        break
        
cap.release()
cv2.destroyAllWindows()

In [38]:
cap = cv2.VideoCapture(0)

while cap.isOpened():
    ret, frame = cap.read()
    if ret:
        
        image = cv2.resize(frame,(400 ,500))
    
        cv2.imshow('video player',image)
        
        if cv2.waitKey(25) & 0xff == ord('q'):
            break
    else:
        break
        
cap.release()
cv2.destroyAllWindows()

In [42]:

cap = cv2.VideoCapture(0)

while cap.isOpened():
    ret, frame = cap.read()
    if ret:
        
        image = cv2.resize(frame,(400 ,250))
        
        frame2 = np.hstack((image, image))
        frame3 = np.vstack((frame2, frame2))
    
        cv2.imshow('video player',frame3)
        
        if cv2.waitKey(25) & 0xff == ord('q'):
            break
    else:
        break
        
cap.release()
cv2.destroyAllWindows()

In [55]:
import cv2
import numpy as np
import os

video_path1 = r"C:\Users\aksha_0iafvb0\OneDrive\Desktop\photos\IMG_2582.MOV"
video_path2 = r"C:\Users\aksha_0iafvb0\Downloads\videoplayback.webm"

cap1 = cv2.VideoCapture(0)  # Webcam
cap2 = cv2.VideoCapture(video_path2)  # Video file 1
cap3 = cv2.VideoCapture(video_path1)  # Video file 2

while cap1.isOpened() and cap2.isOpened() and cap3.isOpened():
    ret1, frame1 = cap1.read()
    ret2, frame2 = cap2.read()
    ret3, frame3 = cap3.read()
    
    if ret1 and ret2 and ret3:
        frame1 = cv2.resize(frame1, (300, 250))
        frame2 = cv2.resize(frame2, (300, 250))
        frame3 = cv2.resize(frame3, (300, 250))
        
        combined_top = np.hstack((frame1, frame2))
        combined_bottom = np.hstack((frame3, frame3))
        final_frame = np.vstack((combined_top, combined_bottom))
        
        cv2.imshow('Video Player', final_frame)
        
        if cv2.waitKey(25) & 0xFF == ord('q'):
            break
    else:
        break

cap1.release()
cap2.release()
cap3.release()
cv2.destroyAllWindows()


# cv2.imread()
# Read RGB, Grey, Transparent Image


Syntax: cv2.imread(path,flag)

Parameters:

path: Image path

## flag: default value is cv2.IMREAD_COLOR

CV2.IMREAD_COLOR or 1:

reads the image with RGB colors

cv2.IMREAD_GRAYSCALE or 0:

reads the image with gray colors

cv2.IMREAD_UNCHANGED or -1:

It reads the image as is from the source. If the source image is an RGB, it loads the image into array with Red, Green and Blue channels. If the source image is ARGB, It loads the image with three color components along with the alpha or transparency channel.


In [67]:
import cv2

path = 'wallpaper.jpg'
img = cv2.imread(path,1)   # here 0 is for black and white 1 is for color image

print(img.shape)
print(img)
img = cv2.resize(img,(300,400))

cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(1080, 1920, 3)
[[[16 18 18]
  [16 18 18]
  [16 18 18]
  ...
  [ 3  3  3]
  [13 13 13]
  [ 0  0  0]]

 [[36 38 38]
  [36 38 38]
  [36 38 38]
  ...
  [37 37 37]
  [37 37 37]
  [10 10 10]]

 [[36 38 38]
  [36 38 38]
  [36 38 38]
  ...
  [45 45 45]
  [39 39 39]
  [ 4  4  4]]

 ...

 [[35 38 43]
  [35 38 43]
  [35 38 43]
  ...
  [45 45 45]
  [39 39 39]
  [ 4  4  4]]

 [[32 34 42]
  [32 34 42]
  [32 35 40]
  ...
  [45 45 45]
  [37 37 37]
  [ 3  3  3]]

 [[27 29 37]
  [27 29 37]
  [27 29 37]
  ...
  [ 4  4  4]
  [14 14 14]
  [ 0  0  0]]]


# Cv2.imshow() in openCv

## Syntax: cv2.imshow(window name, ndarray)
This function help to show image or numpy array in the form of image



In [69]:
import cv2
import numpy as np

matx = np.zeros((200,200))
matx

cv2.imshow('Zeros matrix',matx)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [70]:
img_path = "wallpaper.jpg"
img = cv2.imread(img_path)

cv2.imshow('image', img)


cv2.waitKey(0)
cv2.destroyAllWindows()

# Cv2.imwrite() 
## Video to image

# How to save image or numpy array as image

# how to convert video into images


In [71]:
import cv2
import numpy as np
import os

# Save numpy array

In [73]:
rand_array = np.random.randint(255,size = (300,600,3))

cv2.imwrite("rand_np_array.png", rand_array)     # to save images we use imwrite() function

img = cv2.imread('rand_np_array.png')
cv2.imshow('image', img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Save Image

In [74]:
img_path = 'wallpaper.jpg'


img = cv2.imread(img_path)
cv2.imshow('image', img)

cv2.imwrite("model_wall.png", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Save Images from Video

In [75]:
import cv2
import os
video_path = r"C:\Users\aksha_0iafvb0\Downloads\videoplayback.webm"

os.mkdir("video_to_image") # create directory

cap = cv2.VideoCapture(video_path) # capture video

img_count = 1
while cap.isOpened():
    ret,frame = cap.read() # read video frame
    
    if not ret:
        print("Unable to read frame")
        break
        
    is_img_write = cv2.imwrite(f'video_to_image{img_count}.jpeg', frame)
    
    if is_img_write:
        print(f'image save at video_to_image\image{img_count}.jpeg')
        
        
    cv2.imshow("video", frame)
    
    cv2.waitKey(25) & 0xff == ord('q')
    img_count += 1
    
cap.release()
cv2.destroyAllWindow()
        

image save at video_to_image\image1.jpeg
image save at video_to_image\image2.jpeg
image save at video_to_image\image3.jpeg
image save at video_to_image\image4.jpeg
image save at video_to_image\image5.jpeg
image save at video_to_image\image6.jpeg
image save at video_to_image\image7.jpeg
image save at video_to_image\image8.jpeg
image save at video_to_image\image9.jpeg
image save at video_to_image\image10.jpeg
image save at video_to_image\image11.jpeg
image save at video_to_image\image12.jpeg
image save at video_to_image\image13.jpeg
image save at video_to_image\image14.jpeg
image save at video_to_image\image15.jpeg
image save at video_to_image\image16.jpeg
image save at video_to_image\image17.jpeg
image save at video_to_image\image18.jpeg
image save at video_to_image\image19.jpeg
image save at video_to_image\image20.jpeg
image save at video_to_image\image21.jpeg
image save at video_to_image\image22.jpeg
image save at video_to_image\image23.jpeg
image save at video_to_image\image24.jpeg
i

KeyboardInterrupt: 

# Create Video from Numpy Array and images

## video from Numpy Array



In [77]:
import numpy as np
import cv2
import os

height = 720
width = 1020
channel = 3

fps = 30
sec = 5 

fourcc = cv2.VideoWriter_fourcc(*'MP42')

video = cv2.VideoWriter('test.mp4', fourcc,float(fps), (width,height))

for frame_count in range(fps*sec):
    img = np.random.randint(0,255,(height,width,channel), dtype = np.uint8)
    video.write(img)

video.release()

# How to write text on Image

Syntax : cv2.putText(image,text,org, font, fontScale, color[,thickness[,line Type[.bttomLeftOrigin]]])

In [3]:
import cv2
import numpy as np
img_path = 'wallpaper.jpg'

image = cv2.imread(img_path)

image = cv2.resize(image, (1000,720))

# these are parameters for putText() function
text = "Wallpaper text"

org = (100,300)
font = cv2.FONT_HERSHEY_COMPLEX
fontScale = 3
color = (255,0,0)
thickness = 3
lineType = cv2.LINE_AA
bottomLeftOrigin = False        # this value is by default false


img_text = cv2.putText(image, text,org, font, fontScale, color, thickness, lineType, bottomLeftOrigin)

cv2.imshow("Image", img_text)
cv2.waitKey(0)
cv2.destroyAllWindows()
                   
           


In [4]:
import cv2
import numpy as np
img_path = 'wallpaper.jpg'

image = cv2.imread(img_path)

image = cv2.resize(image, (1000,720))

# these are parameters for putText() function
text = "Wallpaper text"

org = (100,300)
font = cv2.FONT_HERSHEY_COMPLEX
fontScale = 3
color = (255,0,0)
thickness = 3
lineType = cv2.LINE_AA
bottomLeftOrigin = True     # if true it will show mirror image of text we wrote by defalut it is false


img_text = cv2.putText(image, text,org, font, fontScale, color, thickness, lineType, bottomLeftOrigin)

cv2.imshow("Image", img_text)
cv2.waitKey(0)
cv2.destroyAllWindows()
                   
           


In [9]:
import cv2
import numpy as np
img_path = 'wallpaper.jpg'

image = cv2.imread(img_path)

image = cv2.resize(image, (1000,720))

# these are parameters for putText() function
text = "Model"

org = (100,300)
font = cv2.FONT_HERSHEY_COMPLEX
fontScale = 3
color = (0,255,0)
thickness = 3
lineType = cv2.LINE_AA
bottomLeftOrigin = True     # if true it will show mirror image of text we wrote by defalut it is false


img_text = cv2.putText(image, text,org, font, fontScale, color, thickness, lineType, bottomLeftOrigin)
img_text = cv2.putText(image, text,org, font, fontScale, color, thickness, lineType, bottomLeftOrigin= False) 

cv2.imshow("Image", img_text)
cv2.waitKey(0)
cv2.destroyAllWindows()
                   
           


# Rectangle And Text on Image

In [33]:
# Draw Rectangle on Image
import cv2
import numpy as np
img_path = r"C:\Users\aksha_0iafvb0\Downloads\portfolio1.png"

image = cv2.imread(img_path)
image = cv2.resize(image,(1000,600))

#rectangle(img, pt1, pt2, color[,thickness[, lineType [, shift]]])

pt1 = (350,250)
pt2 = (600, 400)
color = (0,255, 0)
thickness = 2        
lineType = cv2.LINE_4

img_rect = cv2.rectangle(image, pt1, pt2, color, thickness, lineType)

cv2.imshow("Image", img_rect)
cv2.waitKey(0)
cv2.destroyAllWindows()




In [36]:
# Fill Rectangle on Image
import cv2
import numpy as np
img_path = r"C:\Users\aksha_0iafvb0\Downloads\portfolio1.png"

image = cv2.imread(img_path)
image = cv2.resize(image,(1000,600))

#rectangle(img, pt1, pt2, color[,thickness[, lineType [, shift]]])

pt1 = (350,250)
pt2 = (600, 400)
color = (200,0, 0)
thickness = -1        # if we give -1 in thickness it will fill the rectangle with color we will give
lineType = cv2.LINE_4

img_rect = cv2.rectangle(image, pt1, pt2, color, thickness, lineType)

cv2.imshow("Image", img_rect)
cv2.waitKey(0)
cv2.destroyAllWindows()




In [40]:
# draw rectangle and also write text inside the rectangle
import cv2
import numpy as np
img_path = r"C:\Users\aksha_0iafvb0\Downloads\portfolio1.png"

image = cv2.imread(img_path)
image = cv2.resize(image,(1000,600))

#rectangle(img, pt1, pt2, color[,thickness[, lineType [, shift]]])

pt1 = (350,250)
pt2 = (600, 400)
color = (200,0, 0)
thickness =  3       # if we give -1 in thickness it will fill the rectangle with color we will give
lineType = cv2.LINE_4

img_rect = cv2.rectangle(image, pt1, pt2, color, thickness, lineType)

# text on image
text = "Hey Anurag"

org = (400,300)
font = cv2.FONT_HERSHEY_COMPLEX
fontScale = 1
color = (0,0,180)
thickness = 1
lineType = cv2.LINE_AA
bottomLeftOrigin = False   # if true it will show mirror image of text we wrote by defalut it is false


img_text = cv2.putText(img_rect, text,org, font, fontScale, color, thickness, lineType, bottomLeftOrigin)


cv2.imshow("Image", img_text)
cv2.waitKey(0)
cv2.destroyAllWindows()




In [43]:
# draw rectangle and also write text above the rectangle
import cv2
import numpy as np
img_path = r"C:\Users\aksha_0iafvb0\Downloads\portfolio1.png"

image = cv2.imread(img_path)
image = cv2.resize(image,(1000,600))

#rectangle(img, pt1, pt2, color[,thickness[, lineType [, shift]]])

pt1 = (350,250)
pt2 = (600, 400)
color = (200,0, 0)
thickness =  3       # if we give -1 in thickness it will fill the rectangle with color we will give
lineType = cv2.LINE_4

img_rect = cv2.rectangle(image, pt1, pt2, color, thickness, lineType)

# text on image
text = "Hey Anurag"

org = (340,240)
font = cv2.FONT_HERSHEY_COMPLEX
fontScale = 1
color = (0,0,180)
thickness = 1
lineType = cv2.LINE_AA
bottomLeftOrigin = False   # if true it will show mirror image of text we wrote by defalut it is false


img_text = cv2.putText(img_rect, text,org, font, fontScale, color, thickness, lineType, bottomLeftOrigin)


cv2.imwrite("image_detect.png",img_text)  # remember always give extension like png, jpeg etc

cv2.imshow("Image", img_text)
cv2.waitKey(0)
cv2.destroyAllWindows()




# Circle & Text on image

In [60]:
import cv2
img_path = r"C:\Users\aksha_0iafvb0\Downloads\portfolio1.png"

image = cv2.imread(img_path)
img_resize = cv2.resize(image,(1000,600))

center = (470,350)
radius = 120
color = (0,255,0)
thickness = 3
lineType = cv2.LINE_4
shift = 0

circle_img = cv2.circle(img_resize,center, radius, color, thickness, lineType, shift)

cv2.imshow("model Image", circle_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Line on Image

In [70]:
import cv2
img_path =  r"C:\Users\aksha_0iafvb0\Downloads\portfolio1.png"

image = cv2.imread(img_path)
img_resize = cv2.resize(image,(1000,600))

pt1 = (180,400)
pt2 = ( 500,300)

color = (0,255,0)
thickness = 3
lineType = cv2.LINE_4
shift = 0

line_img = cv2.line(img_resize,pt1,pt2,color, thickness,lineType, shift)

cv2.imshow("model Image", line_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# how to convert image color using cv2.cvtColor() function

In [77]:
import cv2
img_path = 'wallpaper.jpg'

image = cv2.imread(img_path)
img_resize = cv2.resize(image,(1000,600))

img_color = cv2.cvtColor(img_resize, cv2.COLOR_BGR2GRAY)

cv2.imshow("model Image", img_color)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [72]:
img_resize.shape

(600, 1000, 3)

In [73]:
img_resize[:,:,0]

array([[24, 24, 24, ..., 16, 15, 12],
       [36, 36, 36, ..., 38, 42, 20],
       [35, 35, 35, ..., 40, 37, 16],
       ...,
       [37, 37, 37, ..., 42, 39, 19],
       [35, 35, 35, ..., 35, 41, 20],
       [29, 29, 29, ..., 17, 19, 11]], dtype=uint8)

In [74]:
img_resize[:,:,1]

array([[26, 26, 26, ..., 16, 15, 12],
       [38, 38, 38, ..., 38, 42, 20],
       [37, 37, 37, ..., 40, 37, 16],
       ...,
       [36, 36, 36, ..., 42, 39, 19],
       [38, 38, 38, ..., 35, 41, 20],
       [31, 31, 32, ..., 17, 19, 11]], dtype=uint8)

In [75]:
img_resize[:,:,2]

array([[26, 26, 26, ..., 16, 15, 12],
       [38, 38, 38, ..., 38, 42, 20],
       [37, 37, 37, ..., 40, 37, 16],
       ...,
       [39, 38, 38, ..., 42, 39, 19],
       [42, 42, 42, ..., 35, 41, 20],
       [39, 37, 37, ..., 17, 19, 11]], dtype=uint8)

In [83]:
import cv2

# Load image
img_path = 'wallpaper.jpg'
image = cv2.imread(img_path)

if image is None:
    print("Error: Unable to load image. Check the file path.")
else:
    # Resize image
    img_resize = cv2.resize(image, (1000, 600))

    # List of valid color conversion codes
    img_color = [cv2.COLOR_BGR2HSV, cv2.COLOR_BGR2GRAY, cv2.COLOR_BGR2RGB]

    for color_number in img_color:
        print("Color number:", color_number)

        # Convert image
        color_image = cv2.cvtColor(img_resize, color_number)

        # Show image
        cv2.imshow("Converted Image", color_image)
        cv2.waitKey(0)
        cv2.destroyAllWindows()


Color number: 40
Color number: 6
Color number: 4


# Split & Merge Image

## How to split Image in single channel & Merge multiple single channel?

In [84]:
import cv2
import numpy as np
img_path = 'wallpaper.jpg'

img = cv2.imread(img_path)
img = cv2.resize(img,(1000,720))

cv2.imshow("model Image", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Split image using numpy indexing

In [85]:
img

array([[[21, 23, 23],
        [21, 23, 23],
        [21, 23, 23],
        ...,
        [11, 11, 11],
        [10, 10, 10],
        [10, 10, 10]],

       [[36, 38, 38],
        [36, 38, 38],
        [36, 38, 38],
        ...,
        [37, 37, 37],
        [41, 41, 41],
        [21, 21, 21]],

       [[35, 37, 37],
        [35, 37, 37],
        [35, 37, 37],
        ...,
        [37, 37, 37],
        [38, 38, 38],
        [17, 17, 17]],

       ...,

       [[36, 37, 41],
        [36, 37, 40],
        [36, 37, 40],
        ...,
        [36, 36, 36],
        [35, 35, 35],
        [20, 20, 20]],

       [[34, 37, 43],
        [34, 37, 42],
        [34, 37, 41],
        ...,
        [37, 37, 37],
        [43, 43, 43],
        [20, 20, 20]],

       [[28, 30, 38],
        [28, 31, 37],
        [28, 31, 36],
        ...,
        [11, 11, 11],
        [13, 13, 13],
        [ 9,  9,  9]]], dtype=uint8)

In [86]:
img.shape

(720, 1000, 3)

In [87]:
img[:, :, 0]

array([[21, 21, 21, ..., 11, 10, 10],
       [36, 36, 36, ..., 37, 41, 21],
       [35, 35, 35, ..., 37, 38, 17],
       ...,
       [36, 36, 36, ..., 36, 35, 20],
       [34, 34, 34, ..., 37, 43, 20],
       [28, 28, 28, ..., 11, 13,  9]], dtype=uint8)

In [88]:
img[:, :, 0].shape

(720, 1000)

In [89]:
img[:, :, 1]

array([[23, 23, 23, ..., 11, 10, 10],
       [38, 38, 38, ..., 37, 41, 21],
       [37, 37, 37, ..., 37, 38, 17],
       ...,
       [37, 37, 37, ..., 36, 35, 20],
       [37, 37, 37, ..., 37, 43, 20],
       [30, 31, 31, ..., 11, 13,  9]], dtype=uint8)

In [90]:
img[:, :, 1].shape

(720, 1000)

In [91]:
img[:, :, 2]

array([[23, 23, 23, ..., 11, 10, 10],
       [38, 38, 38, ..., 37, 41, 21],
       [37, 37, 37, ..., 37, 38, 17],
       ...,
       [41, 40, 40, ..., 36, 35, 20],
       [43, 42, 41, ..., 37, 43, 20],
       [38, 37, 36, ..., 11, 13,  9]], dtype=uint8)

In [92]:
img[:, :, 2].shape

(720, 1000)

## split image using cv2.split()

In [93]:
import cv2
import numpy as np
img_path = 'wallpaper.jpg'

img = cv2.imread(img_path)
img = cv2.resize(img,(1000,720))

cv2.imshow("model Image", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [94]:
b, g, r = cv2.split(img)

In [95]:
b

array([[21, 21, 21, ..., 11, 10, 10],
       [36, 36, 36, ..., 37, 41, 21],
       [35, 35, 35, ..., 37, 38, 17],
       ...,
       [36, 36, 36, ..., 36, 35, 20],
       [34, 34, 34, ..., 37, 43, 20],
       [28, 28, 28, ..., 11, 13,  9]], dtype=uint8)

## Show single channel


In [98]:
import cv2
import numpy as np
img_path = 'wallpaper.jpg'

img = cv2.imread(img_path)
img = cv2.resize(img,(300,300))

cv2.imshow("model Image Blue", img[:,:,0])
cv2.imshow("model Image green", img[:,:,1])
cv2.imshow("model Image red", img[:,:,2])


cv2.waitKey(0)
cv2.destroyAllWindows()

In [99]:
import cv2
import numpy as np
img_path = 'wallpaper.jpg'

img = cv2.imread(img_path)
img = cv2.resize(img,(300,300))

b,g,r = cv2.split(img)
cv2.imshow("model Image Blue", b)
cv2.imshow("model Image green", g)
cv2.imshow("model Image red", r)


cv2.waitKey(0)
cv2.destroyAllWindows()

# Merge Image using cv2

In [101]:
img_merge = cv2.merge([b,g,r])

In [102]:
img_merge.shape

(300, 300, 3)

In [103]:
import cv2
import numpy as np
img_path = 'wallpaper.jpg'

img = cv2.imread(img_path)
img = cv2.resize(img,(300,300))

b, g, r = cv2.split(img)

img_merge = cv2.merge([b,g,r])


cv2.imshow("model Image Blue", b)
cv2.imshow("model Image green", g)
cv2.imshow("model Image red", r)

cv2.imshow("Merge Model Image", img_merge)


cv2.waitKey(0)
cv2.destroyAllWindows()

# Blue image

In [105]:
import cv2
import numpy as np
img_path = 'wallpaper.jpg'

img = cv2.imread(img_path)
img = cv2.resize(img,(300,300))

b, g, r = cv2.split(img)

zeros_ch = np.zeros(img.shape[0:2], dtype="uint8")


img_merge = cv2.merge([b,zeros_ch,zeros_ch])




cv2.imshow("Blue Model Image", img_merge)


cv2.waitKey(0)
cv2.destroyAllWindows()

# Green Image

In [106]:
import cv2
import numpy as np
img_path = 'wallpaper.jpg'

img = cv2.imread(img_path)
img = cv2.resize(img,(300,300))

b, g, r = cv2.split(img)

zeros_ch = np.zeros(img.shape[0:2], dtype="uint8")


img_merge = cv2.merge([zeros_ch,g,zeros_ch])




cv2.imshow("Green Model Image", img_merge)


cv2.waitKey(0)
cv2.destroyAllWindows()

# Red image


In [108]:
import cv2
import numpy as np
img_path = 'wallpaper.jpg'

img = cv2.imread(img_path)
img = cv2.resize(img,(300,300))

b, g, r = cv2.split(img)

zeros_ch = np.zeros(img.shape[0:2], dtype="uint8")


img_merge = cv2.merge([zeros_ch,zeros_ch,r])




cv2.imshow("Red Model Image", img_merge)


cv2.waitKey(0)
cv2.destroyAllWindows()

# Show Image using index spliting and 4 image in one window

In [ ]:
# we can do this by using vstack() and hstack() function

 # How to show Histogram of Image
 
 You can consider histogram as a graph or plot, which gives you an overall idea about the intensity distribution of an image. It is a plot with pixel values (ranging from 0 to 255, not always) in X-axis and corresponding number of pixels in the image on Y-axis.

# Blur image using opencv

# Change Image file extension

## JPG, PSD, MP4, PNG, HTML, CSS, JS, PDF, AI, ID, PHP, TIFF


### Supported Image file format by OpenCv

windows bitmaps - *.bmp, *.dib (always supported)
JPEG files - *.jpeg, *.jpg, *.jpe (see the Notes section)
JPEG 2000 files - *jp2 (see te notes section)
Portable Network Graphics - *.pbm, *.pgm, *.ppm (always supported)
Portable image format - *.pbm, *.pgm, *.ppm (always supported)
Sun rasters - *.sr, *.ras (always supported)
TIFF files - *.tiff, *.tif ( see the Notes Section)

In [109]:
import cv2
import numpy as np
img_path = 'wallpaper.jpg'
img = cv2.imread(img_path)


cv2.imshow("image", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Change Image extension JPG to PNG

In [110]:
img_output_path = 'wallpaper.png'
response = cv2.imwrite(img_output_path, img)

if response:
    print("image stored at location:", img_output_path)

image stored at location: wallpaper.png


## Change image extension PNG to JPG

In [111]:
import cv2
import numpy as np
img_path = 'wallpaper.png'
img = cv2.imread(img_path)


cv2.imshow("image", img)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [112]:
img_output_path = 'wallpaper2.jpg'
response = cv2.imwrite(img_output_path, img)

if response:
    print("image stored at location:", img_output_path)

image stored at location: wallpaper.jpg
